# Generated by Django 4.2.2 on 2024-07-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                help_text="Укажите ID чата в Телеграм",
                max_length=35,
                verbose_name="ID чата в Телеграм",
            ),
        ),
    ]